#!/usr/bin/env python3

import os

cwd = os.getcwd()
selected_files = os.environ['NAUTILUS_SCRIPT_SELECTED_FILE_PATHS']
selected_files = selected_files.split('\n')[:-1]

print('The script was run from', cwd)
print('The selected files/folders:\n', selected_files)
